Update fossid_integration_stateless_diffscan.yml debug fossid-toolbox

diff --git a/.github/workflows/fossid_integration_stateless_diffscan.yml b/.github/workflows/fossid_integration_stateless_diffscan.yml
--- a/.github/workflows/fossid_integration_stateless_diffscan.yml
+++ b/.github/workflows/fossid_integration_stateless_diffscan.yml
@@ -32,6 +32,12 @@ jobs:
           sparse-checkout: |
             ignored_projects_list
           ref: feature/new_fossid_ignore_list
+          
+      - name: Debug fossid-toolbox # adding step to check 
+        run: |
+          echo "Checking for fossid-toolbox..."
+          which fossid-toolbox || echo "fossid Not found"
+          
       - name: Run fossid-toolbox
         env:
           FOSSID_HOST_USERNAME: ${{ secrets.FOSSID_HOST_USERNAME }}
